### ISSUE TITLE
[Certificate Install Error]

### ISSUE THREAD

**Issue by philhk** [PsychoPast/LawinServer#1]
Everytime i try to start the program im getting this error

`Thanks for using LawinServer made by Lawin#0001 :D
This launcher was made for LawinServer by PsychoPast.
Running... PLEASE, don't close the window else the connection will be aborted.
[Certificate Install Error] Could not install the certificate. Please restart the app and try again!
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at Microsoft.Win32.RegistryKey.SetValue(String name, Object value, RegistryValueKind valueKind)
   at Microsoft.Win32.Registry.SetValue(String keyName, String valueName, Object value, RegistryValueKind valueKind)
   at LawinServer.Net.Proxy.ResetProxySettings()
   at LawinServer.Net.Proxy.StopProxy()
   at LawinServer.Net.Proxy..ctor(UInt16 port)
   at LawinServer.Net.Proxy..ctor()
   at LawinServer.Program.Run(Nullable`1 port)
   at LawinServer.Program.Main(String[] args)`

**Comment by PsychoPast** [comment]
Hi. Kindly try this solution

![](https://cdn.discordapp.com/attachments/598843403878268938/735188910388412566/unknown.png)

**Comment by PsychoPast** [comment]
Hi. Kindly try this solution:
1) Run CMD as admin
2) Paste in it "reg delete HKLM\Software\Policies\Microsoft\SystemCertificate\Root\ProtectedRoots /f" and press enter 
3) Open LawinServer

**Comment by philhk** [comment]
When i try this it says: ERROR: The specified registry key or value was not found.

**Comment by PsychoPast** [comment]
reg delete HKLM\Software\Policies\Microsoft\SystemCertificates\Root\ProtectedRoots /f
I did a typo my bad

**Comment by philhk** [comment]
Now i cant use Chrome anymore but the program works. Every Website im trying to Access says NET::ERR_CERT_AUTHORITY_INVALID
